### ISSUE TITLE
QR overflows

### ISSUE THREAD

**Issue by scgbckbone** [coinkite/mpy-qr#8]
* all QR codes have this strange left overflow

![snapshot-327-134214](https://github.com/coinkite/mpy-qr/assets/25349625/d7e1e8d3-03d3-43d7-8a89-cf675c23c1b4)

![snapshot-327-134220](https://github.com/coinkite/mpy-qr/assets/25349625/2255f583-fe47-45c5-a929-20af8bc338fb)

![snapshot-327-134223](https://github.com/coinkite/mpy-qr/assets/25349625/f3c02027-0549-4b4e-a490-b77ff9a03c4c)

it is hard to see, but definitely a bug - not sure where.

QR codes are valid anyways

**Comment by doc-hex** [comment]
that's a feature. it's an index number when using the address explorer. iirc it was more visible with p2pkh addresses. 

should probably be removed (Q has space to do right, and does)
